language: en-US
tone_instructions: |
  Invert: Ask "What would make this fail?" not "Is this good?" Be direct.
  Explain failure modes and suggest prevention.

reviews:
  profile: assertive
  collapse_walkthrough: false
  poem: false
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  abort_on_close: true
  review_status: false

  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
    ignore_title_keywords:
      - "WIP"
      - "[WIP]"
      - "DO NOT MERGE"

  path_filters:
    - "!**/__pycache__/**"
    - "!**/.venv/**"
    - "!**/.pytest_cache/**"
    - "!**/.ruff_cache/**"
    - "!**/dist/**"
    - "!**/*.egg-info/**"
    - "!**/htmlcov/**"
    - "!**/.coverage"
    - "!**/uv.lock"

  path_instructions:
    - path: "src/pcp_mcp/**/*.py"
      instructions: |
        pcp-mcp: MCP server for Performance Co-Pilot. Python 3.10+, FastMCP 2.0+.

        INVERSION CHECKLIST - What would cause this to fail?

        MCP server failures to prevent:
        - Tools not returning proper Pydantic response models
        - Not handling httpx exceptions (convert to ToolError)
        - Blocking calls in async tool functions
        - Missing type hints or docstrings
        - Rate calculation errors (counter vs gauge metrics)

        FastMCP patterns to enforce:
        - Tools use @mcp.tool() decorator
        - Resources use @mcp.resource() decorator
        - Context accessed via ctx.request_context.lifespan_context
        - Errors raised as ToolError or ResourceError

        Don't nitpick: ruff handles style, ty handles types.

    - path: "src/pcp_mcp/client.py"
      instructions: |
        Async httpx wrapper for pmproxy REST API.

        INVERSION: What would cause the client to fail?
        - Not creating pmapi context on __aenter__
        - Not closing httpx client on __aexit__
        - Rate calculation with wrong elapsed time
        - Not handling counter wrap-around
        - Timeout not respected

    - path: "src/pcp_mcp/tools/**/*.py"
      instructions: |
        MCP Tools - the core functionality.

        INVERSION: What would cause tools to fail?
        - Exceptions not mapped to ToolError via handle_pcp_error()
        - Missing Annotated[type, Field(...)] for parameter descriptions
        - sample_interval too short for accurate rates
        - Not awaiting async calls

    - path: "src/pcp_mcp/resources/**/*.py"
      instructions: |
        MCP Resources - read-only data browsing.

        INVERSION: What would cause resources to fail?
        - Resources attempting write operations (they're read-only!)
        - Resource URI patterns not matching expected format
        - Not handling missing metrics gracefully

    - path: "src/pcp_mcp/config.py"
      instructions: |
        Configuration via pydantic-settings.

        INVERSION: What would cause config to fail?
        - Missing env_prefix="PCP_" (env vars won't load)
        - Credentials logged or exposed in error messages
        - Invalid defaults for pmproxy connection

    - path: "src/pcp_mcp/errors.py"
      instructions: |
        Error mapping from httpx to MCP.

        INVERSION: What would make error handling fail?
        - Not handling all httpx exception types
        - Generic except clauses hiding real errors
        - Error messages too vague for debugging

    - path: "tests/**/*.py"
      instructions: |
        pytest with pytest-asyncio (asyncio_mode = "auto").

        INVERSION: What would make these tests meaningless?
        - Tests that pass but don't assert meaningful outcomes
        - Mocks without spec= (won't catch attribute errors)
        - Missing edge cases: empty responses, network errors
        - Not using respx for httpx mocking

    - path: "pyproject.toml"
      instructions: |
        Project configuration. Uses uv, ruff, ty, pytest.

        INVERSION: What would break the build/test cycle?
        - Missing dev dependencies
        - pytest-asyncio missing asyncio_mode = "auto"
        - ruff missing D rules for docstrings

chat:
  auto_reply: true

knowledge_base:
  learnings:
    scope: global
