name: Commit Lint

on:
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

      - name: Install commitizen
        run: uv tool install commitizen

      - name: Validate commits
        run: cz check --rev-range origin/${{ github.base_ref }}..HEAD
